name: PR Automatic Labeler

on:
  pull_request:
    types: [opened, labeled, edited, unlabeled]
  issue_comment:
    types: [edited]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Automatic Labeler
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('.github/workflows/labeler.js')
            await script({github, context, core})
